version: '3.8'
services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3332:3332"

  frontend1:
    image: meu-frontend:latest
    container_name: frontend1
    environment:
      - SERVER_NAME=Servidor 1
    ports:
      - "5001:80"
    depends_on:
      - backend

  frontend2:
    image: meu-frontend:latest
    container_name: frontend2
    environment:
      - SERVER_NAME=Servidor 2
    ports:
      - "5002:80"
    depends_on:
      - backend

  frontend3:
    image: meu-frontend:latest
    container_name: frontend3
    environment:
      - SERVER_NAME=Servidor 3
    ports:
      - "5003:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    ports:
      - "8080:80"
  #    - "10.0.0.1:8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
