version: '3.8'
services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3332:3332"

  frontend1:
    container_name: frontend1
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SERVER_NAME: "Servidor 1"
    ports:
      - "8080:80"
    depends_on:
      - backend

  frontend2:
    container_name: frontend2
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SERVER_NAME: "Servidor 2"
    ports:
      - "8081:80"
    depends_on:
      - backend

  frontend3:
    container_name: frontend3
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SERVER_NAME: "Servidor 3"
    ports:
      - "8082:80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
