version: '3.8'
services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3332:3332"

   frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: meu-usuario/frontend-shared:latest
    environment:
      - VITE_SERVER_NAME=${SERVER_NAME}   # opcional, veremos abaixo
    expose:
      - "80"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro